#!/bin/bash


PATH=/usr/bin:/home/pi/wiringPi/gpio

echo "ATXRaspi shutdown script starting..."
echo "Asserting pins (28=in,low; 29=out,high)"

gpio -g mode 28 in
gpio -g write 28 0
gpio -g mode 29 out
gpio -g write 29 1

while [ 1 ]; do
  if [ "$(/home/pi/wiringPi/gpio/gpio -g read 28)" = "1" ]; then
    echo "PIN28 requested a SYSTEM HALT !"
    sudo poweroff
    break
  fi
  /bin/sleep 0.5
done

exit 0
